### ISSUE TITLE
tool rename?

### ISSUE THREAD

**Issue by kestewart** [goneall/cdx2spdx#19]
To make it clearer what this tool does by looking at it,  suggest renaming CDX2SPDX.    SpdxCyclone could be interpreted as SPDX to CycloneDX.    Cyclone doesn't mean much on it's own, and there seems to be a shift to using CDX to summarize the Cyclone Data eXchange format.

**Comment by goneall** [comment]
@kestewart Really good point - I'll rename it before moving it over to the SPDX repo.  I'll probably use cdx2spdx (lowercase) just to be consistent with other SPDX project names.

**Comment by goneall** [comment]
Renamed
